### ISSUE TITLE
Retry if a non-5xx error code is received

### ISSUE THREAD

**Issue by djmcdonald** [bbc/flashheart#1]
We'd like to pass in an array of HTTP status codes (when the client is created) that might trigger a retry (non error codes). Would you guys be OK with this? 

Happy to do the work myself.

**Comment by robinjmurphy** [comment]
Hi @djmcdonald,

Which error codes are you thinking of?

We currently consider anything greater than or equal to 400 an error (https://github.com/bbc/flashheart/blob/master/lib/client.js#L103) and we won't retry a 4XX request because it requires the client to change the request somehow.

**Comment by djmcdonald** [comment]
Hey @robinjmurphy - thanks for getting back to me.

In our case we'd like to retry on a 202, so something like the following:
```javascript
var client = require('flashheart').createClient({
  name: 'my_service',
  additionalRetryCodes: [ 202, ... ]
});
```

**Comment by robinjmurphy** [comment]
I'm a little reluctant to use the exact same logic for a 202.

I'm not sure, for example, that you'd want the same number of retries in an error case as for a 202. You might also want to use a different delay between retries. I don't think you'd want to retry a 202 on a PUT or DELETE either. Potentially only on a GET.

The client doesn't return you the status code or the response object (this was a conscious decision to simplify return values) so if you're working with a service that returns 202's it doesn't currently offer you the chance to implement retries yourself which isn't great.

Let me have a think... It would be good to get decent support for 202 retries in behind an option, I just don't think we'll be able to blindly reuse the error handling logic.

Any thoughts @hjerling or @nspragg?

**Comment by nspragg** [comment]
Retries should only be for actual errors. However, I think it would be a good idea to handle 202's as a separate feature.

**Comment by djmcdonald** [comment]
I'd be happy to add that if you guys are OK with it?

**Comment by robinjmurphy** [comment]
Would certainly be good to see how we might do it. Maybe you could send us some example code of how you'd like it to work? If we can agree on how it's going to look for a user of the library first then you can go off an implement.

**Comment by robinjmurphy** [comment]
Closing this issue as there's not been any activity for a while.
