### ISSUE TITLE
Number of attempts being a timing stat doesn't seem right

### ISSUE THREAD

**Issue by MamathaNair** [bbc/flashheart#32]
In lib/client.js, the stats for number of attempts are send as a timing stat.
  
https://github.com/bbc/flashheart/blob/a448d38328b8d9165ab75096b4af2f01f72e88df/lib/client.js#L180

**Comment by robinjmurphy** [comment]
Hi @MamathaNair. Yep that's on purpose. It may seem a little counter-intuitive but it means you can get a mean, max, min etc. for the value. Are you having a particular issue with it?

**Comment by MamathaNair** [comment]
@robinjmurphy  No it just seemed odd. Thanks for replying.

**Comment by robinjmurphy** [comment]
No worries. This is a graph that we render using the timer.

![screen shot 2016-08-08 at 11 20 22](https://cloud.githubusercontent.com/assets/917111/17476881/24ca22ea-5d5a-11e6-804e-e84d1639e64c.png)
