### ISSUE TITLE
Allow errors to be passed to callback without re-formatting

### ISSUE THREAD

**Issue by Limess** [bbc/flashheart#47]
Allow a flag (`simple` is used by `request-promise` https://github.com/request/request-promise#api-in-detail which defaults to `true`) which prevents formatting errors with a new message, body, etc. when the status code family != 2xx.

### Motivation

Currently we (BBC ID) use our own https://github.com/request/request wrapper, https://github.com/bbc/id-http-client.

We began constructing this before we were aware of Flashheart's existence, and we seem to slowly be bringing it up to feature parity with Flashheart due to product/resilience needs. We'd rather not duplicate these non-product specific features in BBC estate

Ideally we'd be able to instead wrap Flashheart to gain circuit breakers, retries, rate limiting and built-in-cache, and roll our own stats and logs as we see fit (for example for statsd we use datadoghq.com, and the statsd protocol wrapper dogstatsd).

### Problem

Currently we're unable to wrap Flashheart due to the change in error format from standard `request`. We currently have the chain of request decoration, `request -> bbc-http-client-node -> request-promise -> id-http-client`, `request-promise` or `id-http-client` would be unable to interpret the reformatted errors passed via 'errorback'.

If these could be returned as normal, without filtering by statusCode etc, we could in theory consume Flashheart (`request -> bbc-http-client-node -> flashheart -> request-promise -> id-http-client`) while keeping the same API, with new errors thrown by Flashheart falling into `request-promise`' `RequestError` prototype.

**Comment by robinjmurphy** [comment]
Hi @Limess. Thanks for explaining the issue. Are you able to point to the code in Flashheart specifically that is making it impossible for you to use request-promise?

Can you not just promisify Flashheart?

**Comment by Limess** [comment]
From a brief look, https://github.com/bbc/flashheart/blob/master/lib/client.js#L149-L154 would be the blocker for this. 

The reason this affects us is that `request-promise` has a similar approach to Flashheart: converting non `2xx` errors to `StatusCodeErrors` which can then be caught via Bluebird's specific catches or `instanceof` handlers, and  converting errorback errors to `RequestErrors`. If we added Flashheart, these would fall into the latter error type and break our current implementations (this is the key point).

If we were rewriting all our external APIs from the ground up we could consider promisifying instead of using `request-promise` but that would be far too much overhead now.

**Comment by robinjmurphy** [comment]
Closing this as we're not planning to support `request-promise`.

There's some information about promisifying Flashheart here https://github.com/bbc/flashheart#promises
