### ISSUE TITLE
Support with request-promise

### ISSUE THREAD

**Issue by tgoldenberg** [bbc/flashheart#53]
I am trying to use this package with [request-promise](https://github.com/request/request-promise) for requests that look more like this:
```
client.post(url, body).then(res => console.log(res));
```

I'm not able to get this working, but is there any recommended usage with Promises? Thank you.

**Comment by robinjmurphy** [comment]
Hi @tgoldenberg,

I'd suggest promisifying as Flashheart isn't designed to work with `request-promise`. 

We've just made [a change](https://github.com/bbc/flashheart/pull/55) to make [promisification](https://github.com/bbc/flashheart#promises) easier by exposing the `Client` constructor in version `2.6.0`.

```js
const Promise = require('bluebird');
const Client = require('flashheart').Client;
const client = require('flashheart').createClient();

Promise.promisifyAll(Client.prototype);

client.getAsync('http://httpstat.us/200')
  .then((body) => console.log(body));
```
