### ISSUE TITLE
Can you expose when a request is cached?

### ISSUE THREAD

**Issue by Jayflux** [bbc/flashheart#65]
We want to be able to monitor when we make a cold call to an API, but not monitor cached calls. It's hard for us to know when a response is coming from a cache or whether it comes from the real thing (as this logic is buried within the API).

Are you able to expose some flag to say whether the response was cached or not? Or is this already possible and i don't know how to do it _pings_ @nspragg 

It would be nice if we could use the stats field, but we use cloudwatch and i don't know if the StatsD stuff works with that

**Comment by nspragg** [comment]
We could expose cache hit/miss via a response header. Although, we're not looking to make changes to the this version unless it's urgent (patches only). We're rewriting a new version, which could expose a cache hit/miss. 

As for stats, if you want to use our existing stats client, you'd need to find cloudwatch support (data sink) for statsD (it uses graphite as it's backend) or write a custom stats object (as discussed). 

The new version of flashheart, will be plugin based, so you should be able to write your own stats plugin.
