### ISSUE TITLE
Does/can getAsync return response in .then call?

### ISSUE THREAD

**Issue by craigharvi3** [bbc/flashheart#66]
Hey guys.

I'm using the `getAsync` function and i'm wondering if its possible to get the full response passed into the `.then`?

Here's my code:

```
this.restClient.getAsync(url, options)
   .then((body) => {
      ....
    })
   .catch((err) => {
      ....
   });
```

If I was using the callback based approach, I could do:

```
this.restClient.get(url, (err, body, res) => {
    ....
});
```

Which would give me access to the response object (including headers and status code). Is it possible to get a handle of this object using `getAsync`?

Thanks.

**Comment by nspragg** [comment]
@craigharvi3 - Yes, that should be possible. One way, is to use bluebird, and pass `multiArgs` set to true in the options object to `.promisifyAll` .  `body` and `res` should be returned in an array. 
```js
this.restClient.getAsync(url, options)
   .then((results) => {
      // results[0] // body
      // results[1] // res
    })
   .catch((err) => {
      ....
   });
```

For further info see:
http://bluebirdjs.com/docs/api/promise.promisifyall.html
