### ISSUE TITLE
Client request headers are overwritten by flashheart

### ISSUE THREAD

**Issue by chetankbbc** [bbc/flashheart#67]
We are trying to pass Client browser's signature (request headers) to our back-end application. As of now what we are observing is the flashheart is overriding the User-Agent header. 
How can we disable flashheart to overwrite certain headers?

**Comment by nspragg** [comment]
If you don't explicitly set the User-Agent, Flashheart will use a default. You can set the headers when instantiating a Flashheart instance via the `.createClient`. 

See the README for further details:
https://github.com/bbc/flashheart#advanced-configuration
