### ISSUE TITLE
unexpected behaviour on 400 error

### ISSUE THREAD

**Issue by leviwheatcroft** [bbc/flashheart#70]
When a ~400 error condition is detected the response 'body' is [not returned in the usual manner](https://github.com/bbc/flashheart/blob/master/lib/client.js#L159). 

I honestly don't know if this is the correct approach for flashheart or not. However, it's not uncommon for an api to return information about an error in the request body. Because `Error.prototype.toStack()` method just dumps the stack, the only way to know that the information you're looking for is stored in a `body` property on `err` is to look through the source.

**Comment by cejast** [comment]
Hi @leviwheatcroft,

We actually have this in our readme (https://github.com/bbc/flashheart#errors)
