### ISSUE TITLE
Initialising with catbox-redis synchronously causes a race condition

### ISSUE THREAD

**Issue by subvertnormality** [bbc/flashheart#72]
Currently the client is created synchronously. In particular, the start function of the Catbox instance is passed `noop` rather than a callback. This has the potential to cause a race condition while the client attempts to connect to Redis when using catbox-redis.

My feeling is that the whole create client function should be async for consistency, but this obviously would be a breaking change and is generally unnecessary when using memory caches.

For this reason I propose to create a `createClientAsync` function and make that available to use separately. I'll raise a PR for you to review.

**Comment by niklasR** [comment]
Hi @subvertnormality 
Thanks for bringing that up. We have not had any issues, but I'll have a look at this.
