### ISSUE TITLE
Confusing options on createClient

### ISSUE THREAD

**Issue by admirkadriu** [bbc/flashheart#80]
The option object passed on createClient should not contain request settings directly.
timeout and User-Agent can be passed on options.default so it's clear that request settings are being overwritten.

https://github.com/bbc/flashheart/blob/97ba592cdaa07e97da47eac65053f2f27f73d33b/lib/client.js#L44

https://github.com/bbc/flashheart/blob/97ba592cdaa07e97da47eac65053f2f27f73d33b/lib/client.js#L47

**Comment by nspragg** [comment]
As of V3, request options are not passed it directly.
