### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by davidc6** [bbc/flashheart#81]
We (Sounds web) are getting vulnerability alerts in rms-client package (https://github.com/bbc/rms-client). When running `yarn audit` it points to flashheart's dependencies. Is it possible to update these dependecies? Thanks

![screen shot 2019-01-17 at 10 59 11](https://user-images.githubusercontent.com/31448563/51314076-f9a6c580-1a46-11e9-9083-7e8f0a22e8a8.png)

![screen shot 2019-01-17 at 11 00 21](https://user-images.githubusercontent.com/31448563/51314133-23f88300-1a47-11e9-9f58-26d58b0a9377.png)

![screen shot 2019-01-17 at 11 01 39](https://user-images.githubusercontent.com/31448563/51314306-4e4a4080-1a47-11e9-80b7-ba6b485ed951.png)

**Comment by nspragg** [comment]
@davidc6 - We happy to accept a PR for this.

**Comment by nspragg** [comment]
Fixed 3.0.3
