### ISSUE TITLE
Missing ./core in v3.1.1

### ISSUE THREAD

**Issue by cloud-hai-vo** [bbc/flashheart#94]
Hi,

I installed the v.3.1.1 and we have an issue in our release package, the current ./core is missing in our release

Will cause error with import 
````js
import { RequestOptions } from 'flashheart/dist/core/restClient';
````

**Comment by nspragg** [comment]
@cloud-hai-vo - I've replicated the issue using `npm publish --dry-run`. Upgrading `npm` seems to have fixed it. 

Released as `3.1.2`
